name: Release simple to NuGet

on:
  push:
    tags:
    - 'simple/v*'

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Get version from tag
      run: |
        TAGVERSION=$(git describe --tags --abbrev=0)
        TAGVERSION=${TAGVERSION#*/}
        echo "TAGVERSION=${TAGVERSION:1}" >> $GITHUB_ENV
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '8.0.x'
    - name: Pack simple with dotnet
      run: dotnet pack Templates/Simple --output nuget-packages-simple --configuration Release -p:PackageVersion=${{ env.TAGVERSION }}
    - name: Push simple with dotnet
      run: dotnet nuget push nuget-packages-simple/*.nupkg --api-key ${{ secrets.NUGETAPIKEY }} --source https://api.nuget.org/v3/index.json --skip-duplicate
