name: Release to NuGet

on:
  push:
    paths:
    - 'VERSION'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.101
    - name: Pack full with dotnet
      run: dotnet pack Templates/Full --output nuget-packages --configuration Release
    - name: Pack simple with dotnet
      run: dotnet pack Templates/Simple --output nuget-packages --configuration Release
    - name: Push with dotnet
      run: dotnet nuget push nuget-packages/*.nupkg --api-key ${{ secrets.NuGetAPIKey }} --source https://api.nuget.org/v3/index.json --skip-duplicate
